development:
  adapter: mysql2
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV["DATABASE_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_SERVICE_PORT"] %>
